/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/Details': RouteRecordInfo<'/Details', '/Details', Record<never, never>, Record<never, never>>,
    '/useDahGallery': RouteRecordInfo<'/useDahGallery', '/useDahGallery', Record<never, never>, Record<never, never>>,
    '/useEvmMetaDataGallery': RouteRecordInfo<'/useEvmMetaDataGallery', '/useEvmMetaDataGallery', Record<never, never>, Record<never, never>>,
    '/useEvmNftGallery': RouteRecordInfo<'/useEvmNftGallery', '/useEvmNftGallery', Record<never, never>, Record<never, never>>,
  }
}
